import { Template } from '../../types/Template'

const sampleTemplateCopy: Template = {
  id: 1,
  name: 'Sample Template',
  imageSrc: 'sampleTemplate.png',
  params: [
    { label: 'main text', type: 'string' },
    { label: 'call to action text', type: 'string' },
  ],
  saved: {
    version: '3.6.3',
    objects: [
      {
        type: 'circle',
        version: '3.6.3',
        originX: 'left',
        originY: 'top',
        left: 368.89,
        top: 194.13,
        width: 80,
        height: 80,
        fill: {
          type: 'radial',
          coords: { x1: 40, y1: 40, x2: 40, y2: 40, r1: 0, r2: 40 },
          colorStops: [
            {
              id: '0',
              color: 'rgb(3, 6, 17)',
              offset: 0.007751937984496125,
            },
            { id: '1', color: 'rgb(0, 41, 255)', offset: 1 },
          ],
          offsetX: 0,
          offsetY: 0,
          gradientUnits: 'pixels',
          gradientTransform: null,
        },
        stroke: '#000',
        strokeWidth: 0,
        strokeDashArray: [15, 15],
        strokeLineCap: 'round',
        strokeDashOffset: 0,
        strokeLineJoin: 'miter',
        strokeMiterLimit: 4,
        scaleX: 2.65,
        scaleY: 2.65,
        angle: 0,
        flipX: false,
        flipY: false,
        opacity: 1,
        shadow: null,
        visible: true,
        clipTo: null,
        backgroundColor: '',
        fillRule: 'nonzero',
        paintFirst: 'fill',
        globalCompositeOperation: 'source-over',
        transformMatrix: null,
        skewX: 0,
        skewY: 0,
        radius: 40,
        startAngle: 0,
        endAngle: 6.283185307179586,
      },
      {
        type: 'polygon',
        version: '3.6.3',
        originX: 'left',
        originY: 'top',
        left: -10.67,
        top: 455.22,
        width: 100,
        height: 100,
        fill: 'black',
        stroke: '#000',
        strokeWidth: 8,
        strokeDashArray: null,
        strokeLineCap: 'butt',
        strokeDashOffset: 0,
        strokeLineJoin: 'miter',
        strokeMiterLimit: 4,
        scaleX: 8.24,
        scaleY: 3.07,
        angle: 0,
        flipX: false,
        flipY: false,
        opacity: 1,
        shadow: null,
        visible: true,
        clipTo: null,
        backgroundColor: '',
        fillRule: 'nonzero',
        paintFirst: 'fill',
        globalCompositeOperation: 'source-over',
        transformMatrix: null,
        skewX: 0,
        skewY: 0,
        points: [
          { x: 0, y: 0 },
          { x: 0, y: 100 },
          { x: 100, y: 100 },
          { x: 100, y: 0 },
        ],
      },
      {
        type: 'textbox',
        version: '3.6.3',
        originX: 'left',
        originY: 'top',
        left: 68.89,
        top: 489.65,
        width: 613,
        height: 122.04,
        fill: '#8fce00',
        stroke: 'rgb(244, 67, 54)',
        strokeWidth: 0,
        strokeDashArray: null,
        strokeLineCap: 'butt',
        strokeDashOffset: 0,
        strokeLineJoin: 'miter',
        strokeMiterLimit: 4,
        scaleX: 1.12,
        scaleY: 1.12,
        angle: 0,
        flipX: false,
        flipY: false,
        opacity: 1,
        shadow: null,
        visible: true,
        clipTo: null,
        backgroundColor: '',
        fillRule: 'nonzero',
        paintFirst: 'fill',
        globalCompositeOperation: 'source-over',
        transformMatrix: null,
        skewX: 0,
        skewY: 0,
        text: 'This is the Template Text',
        fontSize: 50,
        fontWeight: 'normal',
        fontFamily: "'Open Sans', sans-serif",
        fontStyle: 'normal',
        lineHeight: 1.16,
        underline: false,
        overline: false,
        linethrough: false,
        textAlign: 'left',
        textBackgroundColor: '',
        charSpacing: 0,
        minWidth: 20,
        splitByGrapheme: false,
        styles: {},
      },
      {
        type: 'textbox',
        version: '3.6.3',
        originX: 'left',
        originY: 'top',
        left: 415.37,
        top: 237.89,
        width: 124.82,
        height: 126.92,
        fill: '#ce7e00',
        stroke: null,
        strokeWidth: 1,
        strokeDashArray: null,
        strokeLineCap: 'butt',
        strokeDashOffset: 0,
        strokeLineJoin: 'miter',
        strokeMiterLimit: 4,
        scaleX: 1,
        scaleY: 1,
        angle: 0,
        flipX: false,
        flipY: false,
        opacity: 1,
        shadow: null,
        visible: true,
        clipTo: null,
        backgroundColor: '',
        fillRule: 'nonzero',
        paintFirst: 'fill',
        globalCompositeOperation: 'source-over',
        transformMatrix: null,
        skewX: 0,
        skewY: 0,
        text: 'See More',
        fontSize: 52,
        fontWeight: 'normal',
        fontFamily: "'Lucida Console', Monaco, monospace",
        fontStyle: 'normal',
        lineHeight: 1.16,
        underline: false,
        overline: false,
        linethrough: false,
        textAlign: 'left',
        textBackgroundColor: '',
        charSpacing: 0,
        minWidth: 20,
        splitByGrapheme: false,
        styles: {},
      },
    ],
  },
}

export default sampleTemplateCopy
